version: '3.4'

volumes:
  db-avalon:
  fedora:
  solr:
  npms:

networks:
  external:
  internal:

services:
  db-avalon: &db-avalon
    image: postgres:11-alpine
    environment:
      - PGDATA=/data
      - POSTGRES_USER=postgres
      - POSTGRES_DB=avalon
      - POSTGRES_PASSWORD=avalon123
    volumes:
      - db-avalon:/data
    networks:
      internal:
  db-avalon-test:
    <<: *db-avalon
    volumes: []

  fedora: &fedora
    image: avalonmediasystem/fedora:4.7.5
    volumes:
      - fedora:/data
    environment:
      - JAVA_OPTIONS=${JAVA_OPTIONS} -Dfcrepo.modeshape.configuration=classpath:/config/file-simple/repository.json -Dfcrepo.home=/data
    networks:
      internal:
  fedora-test:
    <<: *fedora
    volumes: []

  solr: &solr
    image: solr:6.6.4-alpine
    volumes:
      - ./solr/config:/opt/solr/avalon_conf
      - solr:/opt/solr/server/solr/mycores
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - avalon
      - /opt/solr/avalon_conf
    networks:
      internal:
  solr-test:
    <<: *solr
    volumes: 
      - ./solr/config:/opt/solr/avalon_conf

  hls:
    image: avalonmediasystem/nginx:avalon-7.0
    volumes:
      - ./tmp/derivatives:/data
    ports:
       - "8880:80"
    networks:
      external:

  redis: &redis
    image: redis:alpine
    networks:
      internal:
  redis-test:
    <<: *redis

  avalon: &avalon
    image: avalonmediasystem/avalon:bundle-20210901-sqlite3
    build:
      context: .
      target: dev
      args:
        FITS_VER: 1.4.1
    command: bash -c "/docker_init.sh && rails server -b 0.0.0.0"
    depends_on:
      - db-avalon
      - fedora
      - solr
      - redis
      - hls
    environment:
      - DATABASE_URL=postgresql://postgres:avalon123@db-avalon/avalon
      - REDIS_HOST=redis
      - FEDORA_URL=http://fedora:8080/fedora/rest
      - SOLR_URL=http://solr:8983/solr/avalon
    volumes:
      - .:/home/app/avalon
      - npms:/home/app/avalon/node_modules
    user: $UID
    ports:
      - 3000:3000
      - 8080:8080
    stdin_open: true
    tty: true
    networks:
      external:
      internal:

  test:
    <<: *avalon
    command: >
      bash -c "/docker-init.sh && tail -f /dev/null"
    depends_on:
      - db-avalon-test
      - fedora-test
      - solr-test
      - redis-test
    environment:
      - DATABASE_URL=postgresql://postgres@db-avalon-test/avalon
      - REDIS_HOST=redis-test
      - FEDORA_URL=http://fedora-test:8080/fedora/rest
      - SOLR_URL=http://solr-test:8983/solr/avalon
      - RAILS_ENV=test
      - BUNDLE_FLAGS=--with aws development test --without production
      - DATABASE_CLEANER_ALLOW_REMOTE_DATABASE_URL=true
    volumes: []
