development:
  user: fedoraAdmin
  password: fedoraAdmin
  url: <%= ENV["FEDORA_URL"] || "http://127.0.0.1:#{ENV.fetch('FCREPO_DEVELOPMENT_PORT', 8984)}/rest" %>
  base_path: <%= ENV["FEDORA_BASEPATH"] || "/dev" %>
test:
  user: fedoraAdmin
  password: fedoraAdmin
  url: <%= ENV["FEDORA_URL"] || "http://127.0.0.1:#{ENV.fetch('FCREPO_TEST_PORT', 8986)}/rest" %>
  base_path: <%= ENV["FEDORA_BASEPATH"] || "/test" %>
production:
  user: fedoraAdmin
  password: fedoraAdmin
  url: <%= ENV["FEDORA_URL"] || "http://127.0.0.1:#{ENV.fetch('FCREPO_TEST_PORT', 8984)}/rest" %>
  base_path: <%= ENV["FEDORA_BASEPATH"] || "/prod" %>
